---
- name: create root directory
  file: path={{item}} state=directory
  with_items:
    - /home/www
    - /home/www/{{ deploy_dir}}

- name: create deploy user
  user: name={{ deploy_user }}
        home=/home/www/{{ deploy_user }}
        shell=/bin/bash

- name: create basic directory
  file: path={{item}} state=directory owner={{ deploy_user }} group={{ deploy_user }}
  with_items:
    - "/home/www/{{ deploy_dir}}"
    - "{{ shared_path }}"
    - "{{ shared_path }}/cached-copy"
    - "{{ shared_path }}/app"
    - "{{ shared_path }}/app/config"
    - "{{ shared_path }}/app/logs"

- name: check if the repository is already here
  stat: path={{ shared_path }}/cached-copy/.git
  register: git_stat

- name: git first clone
  git: repo={{ deploy_git_url }}
       dest={{ shared_path }}/cached-copy
       clone=yes
       update=no
       accept_hostkey=true
  sudo: yes
  sudo_user: '{{ deploy_user }}'
  when: git_stat.stat.exists == False

- name: set the log right
  file: path="{{ shared_path }}/app/logs/{{ cluster_env }}.log"
        owner=www-data
        group=www-data
