---
- name: update source git repo
  shell: "git fetch && git reset --hard origin/master"
  sudo: yes
  sudo_user: '{{ deploy_user }}'
  args:
    chdir: "{{ shared_path }}/cached-copy"

- name: Create release directory
  file: "state=directory owner='{{ deploy_user }}' path='{{ release_path }}'"
  sudo: yes
  sudo_user: '{{ deploy_user }}'

- name: copy the cached git copy
  shell: "cp -r {{ shared_path }}/cached-copy/. {{ release_path }}"
  sudo: yes
  sudo_user: '{{ deploy_user }}'

- name: git checkout
  shell: "git checkout {{ deploy_branch }}"
  sudo: yes
  sudo_user: '{{ deploy_user }}'
  args:
    chdir: "{{ release_path }}"
