---
- name: Ensure logs directory is not present.
  file: state=absent 
        path={{ release_path }}/app/logs

- name: Create symlinks to shared directories.
  file: state=link 
        src={{ item.src }} 
        path={{ item.path }}
  with_items:
    - { src: "{{ shared_path }}/app/logs", path: "{{release_path}}/app/logs" }

- name: Check if config dir exists.
  stat: path={{ release_path }}/app/config
  register: config_dir

- name: Link configs dir if not yet exists.
  file: state=link 
        src={{ shared_path }}/shared/app/config 
        path={{ release_path }}/app/config                            
  when: config_dir.stat.exists == false

- name: Check if shared/app/config/parameters.yml exists.
  stat: path={{ shared_path }}/app/config/parameters.yml
  register: parameters_yml

- name: Create symlink for app/config/parameters.yml from shared directory.
  shell: ln -s {{ shared_path }}/app/config/parameters.yml {{ release_path }}/app/config/parameters.yml creates={{ release_path }}/app/config/parameters.yml
  when: parameters_yml.stat.exists
