---
- name: deployment pre tasks (all hosts)
  sudo: yes
  sudo_user: '{{ deploy_user }}'
  shell: >
    cd {{ release_path }} &&
    SYMFONY_ENV={{ cluster_env }}
    {{ item.cmd }}
  run_once: false
  when: >
    ({{ item.run_once | default(false) }} == false) and
    ({{ item.control | default(true) }} != false)
  with_items: deploy_pre_deploy_tasks

- name: deployment pre tasks (single hosts)
  sudo: yes
  sudo_user: '{{ deploy_user }}'
  shell: >
    cd {{ release_path }} &&
    SYMFONY_ENV={{ cluster_env }}
    {{ item.cmd }}
  run_once: true
  when: >
    ({{ item.run_once | default(false) }} == true) and
    ({{ item.control | default(true) }} != false)
  with_items: deploy_pre_deploy_tasks
