- include: "{{ symfony_role_path }}/config/steps/parameters.yml"

- include: "{{ symfony_role_path }}/config/steps/composer.yml"
  when: symfony_run_composer

- include: "{{ symfony_role_path }}/config/steps/schema.yml"
  when: symfony_run_schema_update

- include: "{{ symfony_role_path }}/config/steps/assets.yml"
  when: symfony_run_assets_install

- include: "{{ symfony_role_path }}/config/steps/assetic.yml"
  when: symfony_run_assetic_dump

- include: "{{ symfony_role_path }}/config/steps/cache.yml"
  when: symfony_run_cache_clear_and_warmup

- include: "{{ symfony_role_path }}/config/steps/doctrine.yml"
  when: symfony_run_doctrine_migrations

- include: "{{ symfony_role_path }}/config/steps/mongodb.yml"
  when: symfony_run_mongodb_schema_update

- include: "{{ symfony_role_path }}/config/steps/elastica.yml"
  when: symfony_run_elastica_populate

- include: "{{ symfony_role_path }}/config/steps/liip.yml"
  when: symfony_run_liip_imagine_cache_remove
