---
- name: Make way for shared paths / resources shared across releases
  file:
    state=absent
    path={{ansistrano_release_path.stdout}}/{{item}}
  with_items: "{{ ansistrano_shared_paths }}"
  become: yes
  become_user: "{{ deploy_user }}"
