---
- name: Dump assetic assets
  shell: chdir={{deployment_release_path.stdout}}
    {{symfony_php_path}} app/console assetic:dump --env={{ item }} {{ symfony_assetic_options }}
  become: yes
  become_user: "{{ deploy_user }}"
  when: symfony_run_assetic_dump
  with_items: "{{ symfony_env }}"