---
- name: Install assets
  shell: chdir={{deployment_release_path.stdout}}
    {{symfony_php_path}} app/console assets:install --env={{ item }} {{ symfony_assets_options }}
  become: yes
  become_user: "{{ deploy_user }}"
  when: symfony_run_assets_install
  with_items: "{{ symfony_env }}"