---
- name: Clear cache
  shell: chdir={{deployment_release_path.stdout}}/{{symfony_deployment_subdir}}
    {{symfony_php_path}} {{ symfony_console_path }} cache:clear --no-warmup --env={{ item }} {{symfony_cache_options}}
  when: symfony_run_cache_clear_and_warmup
  become: yes
  become_user: "{{ deploy_user }}"
  with_items: "{{ symfony_env }}"

- name: Warm-up cache
  shell: chdir={{deployment_release_path.stdout}}/{{symfony_deployment_subdir}}
    {{symfony_php_path}} {{ symfony_console_path }} cache:warmup --env={{ item }} {{symfony_cache_options}}
  when: symfony_run_cache_clear_and_warmup
  become: yes
  become_user: "{{ deploy_user }}"
  with_items: "{{ symfony_env }}"
