---
- name: Run Doctrine migrations
  shell: chdir={{deployment_release_path.stdout}}
    SYMFONY_ENV={{symfony_env}} {{symfony_php_path}} app/console doctrine:migrations:migrate --no-interaction {{symfony_doctrine_options}}
  become: yes
  become_user: "{{ deploy_user }}"
