---
- name: Run Doctrine migrations
  shell: chdir={{deployment_release_path.stdout}}
    {{symfony_php_path}} app/console doctrine:migrations:migrate --no-interaction --env=prod {{symfony_doctrine_options}}
  become: yes
  become_user: "{{ deploy_user }}"
