---
- name: Populate elasticsearch with elastica bundle
  shell: chdir={{deployment_release_path.stdout}}
    SYMFONY_ENV={{symfony_env}} {{symfony_php_path}} app/console fos:elastica:populate {{ symfony_elastica_options }}
  when: symfony_run_elastica_populate
  become: yes
  become_user: "{{ deploy_user }}"
  run_once: true
