---
- name: Update MongoDB schema
  shell: chdir={{ansistrano_release_path.stdout}}
    {{symfony_php_path}} {{ symfony_console_path }} doctrine:mongodb:schema:update --env=prod {{symfony_mongodb_options}}
