- name: Copy parameters.yml
  template:
    src="{{ symfony_parameters_template }}"
    dest="{{ ansistrano_release_path.stdout }}/{{ symfony_parameters_name | default('app/config/parameters.yml') }}"
    owner="{{ deploy_user }}"
    group="{{ deploy_user }}"
  when: symfony_run_parameters
  become: yes
  become_user: "{{ deploy_user }}"
