- name: Create /var/www directory
  file: path=/var/www/ state=directory mode=0755 owner=www-data group=www-data

- name: Create reset-cache.php
  lineinfile: dest=/var/www/reset-cache.php regexp="^<?php" line="<?php opcache_reset(); ?>" create=yes owner=www-data group=www-data

- name: Install python-httplib2 to call the url
  pip: name=httplib2

- name: Call reset cache
  uri: url="http://127.0.0.1/reset-cache?pool={{ symfony_reset_cache_pool }}"
