- name: Create /var/www directory
  file: path=/var/www/ state=directory mode=0755 owner=www-data group=www-data

- name: Create reset-cache.php
  lineinfile: dest=/var/www/reset-cache.php regexp="^<?php" line="<?php opcache_reset(); ?>"