---
- name: Doctrine Schema Update
  shell: chdir={{deployment_release_path.stdout}}
    {{symfony_php_path}} app/console doctrine:schema:update --env=prod {{ symfony_schema_options }}
  become: yes
  become_user: "{{ deploy_user }}"
  when: symfony_run_schema_update
  run_once: true