---
- name: Doctrine Schema Update
  shell: chdir={{ansistrano_release_path.stdout}}/{{symfony_deployment_subdir}}
    {{symfony_php_path}} {{ symfony_console_path }} doctrine:schema:update --env=prod {{ symfony_schema_options }}
  become: yes
  become_user: "{{ deploy_user }}"
  when: symfony_run_schema_update
  run_once: true
